import type { Metadata } from "next";
import "./globals.css";
import { mainFont, monoFont } from "../lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${mainFont.variable} ${monoFont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
